packages:
  stock: !include stock_router_2.yaml

esphome:
  name: fast-attach-router-2
  friendly_name: fast-attach-router-2

external_components:
  - source:
      type: local
      path: ../../components
    components: [thread_fast_attach]

thread_fast_attach:
  arm_after_parent_loss: false

thread_parent_response_delay_log:
  enabled: false
